name: hardware_connectivity_repository
description: A Flutter package for handling business logic for accessing nearby hardware devices.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bluetooth_connection_api:
    path: ../bluetooth_connection_api
  usb_connection_api:
    path: ../usb_connection_api
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  mockito: ^5.4.6