name: usb_con_api
description: A Flutter package for USB connection management to the external devices supporting serial connectivity.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  flutter_libserialport: ^0.5.0
  bluetooth_con_api:
    path: ../bluetooth_con_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4