name: network_api
description: A Flutter implementation of the Network API that uses customized mocked http request handler.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  authentication_repository:
    path: ../authentication_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4